//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDOGv2.R2WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/R2Info")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ISRC_Information", Namespace="http://schemas.datacontract.org/2004/07/XML_Downloader")]
    [System.SerializableAttribute()]
    public partial class ISRC_Information : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISRCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISRCIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceReleaseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceUPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Track_ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Track_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grid {
            get {
                return this.GridField;
            }
            set {
                if ((object.ReferenceEquals(this.GridField, value) != true)) {
                    this.GridField = value;
                    this.RaisePropertyChanged("Grid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISRC {
            get {
                return this.ISRCField;
            }
            set {
                if ((object.ReferenceEquals(this.ISRCField, value) != true)) {
                    this.ISRCField = value;
                    this.RaisePropertyChanged("ISRC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISRCId {
            get {
                return this.ISRCIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ISRCIdField, value) != true)) {
                    this.ISRCIdField = value;
                    this.RaisePropertyChanged("ISRCId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceId {
            get {
                return this.ResourceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceIdField, value) != true)) {
                    this.ResourceIdField = value;
                    this.RaisePropertyChanged("ResourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceReleaseId {
            get {
                return this.SourceReleaseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceReleaseIdField, value) != true)) {
                    this.SourceReleaseIdField = value;
                    this.RaisePropertyChanged("SourceReleaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceUPC {
            get {
                return this.SourceUPCField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceUPCField, value) != true)) {
                    this.SourceUPCField = value;
                    this.RaisePropertyChanged("SourceUPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track_Artist {
            get {
                return this.Track_ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.Track_ArtistField, value) != true)) {
                    this.Track_ArtistField = value;
                    this.RaisePropertyChanged("Track_Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track_Title {
            get {
                return this.Track_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Track_TitleField, value) != true)) {
                    this.Track_TitleField = value;
                    this.RaisePropertyChanged("Track_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XML {
            get {
                return this.XMLField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLField, value) != true)) {
                    this.XMLField = value;
                    this.RaisePropertyChanged("XML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="R2WS.IR2InfoServices")]
    public interface IR2InfoServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IR2InfoServices/GetData", ReplyAction="http://tempuri.org/IR2InfoServices/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IR2InfoServices/GetData", ReplyAction="http://tempuri.org/IR2InfoServices/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IR2InfoServices/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IR2InfoServices/GetDataUsingDataContractResponse")]
        SEDOGv2.R2WS.CompositeType GetDataUsingDataContract(SEDOGv2.R2WS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IR2InfoServices/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IR2InfoServices/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SEDOGv2.R2WS.CompositeType> GetDataUsingDataContractAsync(SEDOGv2.R2WS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IR2InfoServices/GetR2ISRCInformation", ReplyAction="http://tempuri.org/IR2InfoServices/GetR2ISRCInformationResponse")]
        SEDOGv2.R2WS.ISRC_Information GetR2ISRCInformation(string isrc, bool withXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IR2InfoServices/GetR2ISRCInformation", ReplyAction="http://tempuri.org/IR2InfoServices/GetR2ISRCInformationResponse")]
        System.Threading.Tasks.Task<SEDOGv2.R2WS.ISRC_Information> GetR2ISRCInformationAsync(string isrc, bool withXML);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IR2InfoServicesChannel : SEDOGv2.R2WS.IR2InfoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class R2InfoServicesClient : System.ServiceModel.ClientBase<SEDOGv2.R2WS.IR2InfoServices>, SEDOGv2.R2WS.IR2InfoServices {
        
        public R2InfoServicesClient() {
        }
        
        public R2InfoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public R2InfoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public R2InfoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public R2InfoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SEDOGv2.R2WS.CompositeType GetDataUsingDataContract(SEDOGv2.R2WS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SEDOGv2.R2WS.CompositeType> GetDataUsingDataContractAsync(SEDOGv2.R2WS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public SEDOGv2.R2WS.ISRC_Information GetR2ISRCInformation(string isrc, bool withXML) {
            return base.Channel.GetR2ISRCInformation(isrc, withXML);
        }
        
        public System.Threading.Tasks.Task<SEDOGv2.R2WS.ISRC_Information> GetR2ISRCInformationAsync(string isrc, bool withXML) {
            return base.Channel.GetR2ISRCInformationAsync(isrc, withXML);
        }
    }
}
